### PR TITLE
Considerable speedup using Nanoflann instead of pcl::KDTreeFLANN 

### PR DESCRIPTION
**Pull request by facontidavide**
Hi,

doing some further profiling I noticed that most of time spent in laserMapping and laserOdometry is spent calculating the nearest neighbors with pcl::KDTreeFLANN.

Just for fun I tested [nanoflann](https://github.com/jlblancoc/nanoflann) and I got very good results.
laserMapping is more or less 2X faster and laserOdometry 1.4X faster.

I modified slightly the code of nanoflann and added an adapter to have a class that resemble exactly the PCL one.

By the way, this PR is based on the PR #24 , so may be you want to merge that first.

### CODE REVIEW

**Comment by jlblancoc** [comment]
As the author of nanoflann, I'm really glad of reading this! :+1:

**Comment by facontidavide** [comment]
@jlblancoc is awesome man. will never use the PCL version again :P

**Comment by laboshinl** [comment]
Hi @facontidavide,
Merged. 
Thank you so much for your contribution, it's nice that the project is actively developing.

**Comment by facontidavide** [comment]
@laboshinl thank you for sharing this code.

But remember, with a lot of Github stars. come great responsibility ;)

Looking at the forks done by people I noticed a common pattern: many, like myself, really dislike hard to read code and magic numbers. It would be very great if you take a look at how other people modify your code and take the opportunity to split your code in smaller and reusable functions.

**Comment by facontidavide** [comment]
yesm we should probably apply the change suggested by @getupgetup , just in case

**Pull request merged**
