### PR TITLE
Lib extration

### PR DESCRIPTION
**Pull request by StefanGlaser**
Extracted all components into separate classes and adapted project structure.

- All loam components are now build into a library (libloam.so)
- ros nodes are reduced to a minimum, only forwarding node handles. ros nodelets should be straight forward to create.
- All component buffers are now dynamic (if logic requires them to be) and automatically resized during processing. This means that the major processing logic should now be independent of the number of scans a lidar produces and the number of extracted features.
- Distributed code across multiple functions and reduced scopes of variables where possible.

This pull request is conflicting with the master branch, due to the previous hotfix that I committed. However, this pull request basically contains the previous hotfix (as it further simplified processing of rotations) and merging by overriding the changes of the hotfix should be fine.

### CODE REVIEW

**Comment by facontidavide** [comment]
Very nice changes !!!

**Comment by jlblancoc** [comment]
Thanks!! 

All ROS pkgs hould be structured like this: a generic library (ideally not using ROS types at all!) + the node wrapper... 

Just my view ;-)

**Comment by StefanGlaser** [comment]
Thanks for your feedback!

However, I have to say that Martin Velas went way further with his branch and introduced significant simplifications. I feel kind of sad that his effort is not honored much and with all the changes I introduced, the chance of merging his branch is even lower than before. I guess the best way of acknowledging his work is to keep up working on LOAM and integrating his improvements, too.

**Comment by facontidavide** [comment]
I agree, but the only one that can really take some actions is Martin Velas himself

**Pull request merged**
