### PR TITLE
Decouples ROS from the core LOAM algorithms.

### PR DESCRIPTION
**Pull request by adishavit**
- Maintains original API.
- Core LOAM algorithm now only depend on PCL and Eigen.
- Uses std::chrono instead of ROS Time (bit-exact change).
- Fixes some minor bugs and inefficiencies.

It's far being as elegant as it could - my goal was to get it to build on Windows too so I could evaluate it in a non-ROS environment - which it does. So this is not the most that can/should be done.
Having more eyeballs on it would be a tremendous help. Especially with documenting the LOAM code flow and logic.

### CODE REVIEW

**Comment by adishavit** [comment]
This is a good idea - I have no problem with setting that up.
My aim was to try and avoid any external changes to the project so that existing users will not need to change their code as all. 
What you suggest only requires moving some files around and fixing a few `CMakeLists.txt` files with new libs and paths. 

I would very much prefer for all of use to work on a single repo and not multiple forks - we are all duplicating work (in fact I had already decoupled ROS from the `daobilige-su/loam_velodyne` repo before finding this one, and had to redo everything again since this project since better maintained (or at least more active).

If there is consensus about proceeding, then we can make the updates and move forward. 
@laboshinl, do you have any input on this?

It seems like this is most active project/repo and it would be a shame to not leverage the work of multiple people and letting them duplicate their effort instead.

**Comment by YoshuaNava** [comment]
Hey,
I totally support what you are saying about contributing to this repository instead of having multiple forks.

Maybe we can make a list of changes and start introducing them one by one.

**Comment by adishavit** [comment]
My list has mainly:
- separate ROS while maintaining backward complatibility
- Bug fixes

Which is what I've done.
I _would_ like to do more refactoring though.

In any case, I'd want feedback from @laboshinl.

@YoshuaNava: What do you have in mind?

**Comment by YoshuaNava** [comment]
Hi @adishavit,
Sorry for the delay. The work you did is great. I think it could be merged, and the refactoring you speak about could be introduced in pull requests after that.

What I have in mind is to put together the spinning lidar and velodyne variants of LOAM, so that they can be used and extended by the community.

@laboshinl, @StefanGlaser what do you think?

**Comment by StefanGlaser** [comment]
Hi all together,  
also sorry from my side for not replying to recent issues and pull requests. I'm just too busy working and finishing my master thesis.
Decoupling LOAM from ROS is certainly a good idea and also one of the top items on my TODO list. One might argue about the best way of doing it, but in the end this project is very much work in progress. So from my point of view, any contribution pushing the project forward is appreciated.

@YoshuaNava seems to be fine with your changes and wants to build upon them, so I don't see any reason to reject your pull request.

**Pull request merged**
