### PR TITLE
Code simplification

### PR DESCRIPTION
**Pull request by facontidavide**

### CODE REVIEW

**Comment by StefanGlaser** [comment]
Hi @facontidavide , thanks for your great contributions to this project! The runtime has improved significantly!

Just wanted to notify you about some code simplifications I recently started in [my fork](https://github.com/StefanGlaser/loam_velodyne). I haven't created a PR yet, but maybe it is useful for you.

**Comment by facontidavide** [comment]
@StefanGlaser I knew already about your fork. the fact that you and other people cared about this, was my motivation to write this issue. I suggest you to send PR to this repository, that would be the best way to help the community

**Comment by facontidavide** [comment]
In general, I believe that the best way to improve the code base is through small and easy to read changes like this, rather than big ones that are hard to review.

Anyway, I will modify this PR and use the same functions you wrote here, to show you that I am not willing to reinvent the wheel :D

**Comment by StefanGlaser** [comment]
@facontidavide well, no hard feelings ;) I'm very happy about the availability of this project and also your contributions. I've just noticed that you started to add similar code cleanups as I did just a couple of days before and wanted to reduce the double effort.

I think this is a great and powerful approach and I would like to get it a) available in ROS again and b) to work with multiple input lidars simultaneously. The code quality is not the best and looking at the recent activity of this project I wasn't expecting to get much support / feedback for simple code refactorings. Anyhow, I agree with you and will prepare a couple of simple PRs, soon.

**Comment by facontidavide** [comment]
the branch has conflicts. I will remove the PR for now.

**Pull request closed without merging**
